### ISSUE TITLE
Support detecting compute nodes of E3SM machines

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/mache#134]
There has been issues raised that when running on compute nodes, analysis tools won't auto detect machines: e.g. https://github.com/E3SM-Project/zppy/issues/406
The suggested solution for now is to manually specify machine name, e.x
```
[default]
machine = chrysalis
```
or if running in E3SM-Unified, to use the environment variable, e.x.
```
machine = os.environ["E3SMU_MACHINE"]
```

It might be viable to detect machines based on compute node names if there is a pattern. Though it can be challenging based on comment from @xylar: https://github.com/E3SM-Project/zppy/pull/511#issuecomment-1730091967

It seems that we can start to add support for certain machines that has patterns in their compute nodes names.

**Comment by xylar** [comment]
Perfect, thanks!  I will give it a try...

**Comment by xylar** [comment]
@chengzhuzhang, we have a backup option already, where we supposedly create a file when mache gets installed and read the machine name from it:
https://github.com/E3SM-Project/mache/blob/main/mache/discover.py#L59-L67
I wonder why that's not working.

**Comment by xylar** [comment]
The answer is that I clearly forgot to implement this on conda-forge.

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang, we have a backup option already, where we supposedly create a file when mache gets installed and read the machine name from it: https://github.com/E3SM-Project/mache/blob/main/mache/discover.py#L59-L67 
>
Smart!

**Comment by xylar** [comment]
This should be fixed in different ways by https://github.com/conda-forge/mache-feedstock/pull/54 and #135.  Hopefully, we really clobber this one once and for all...

**Comment by xylar** [comment]
(Sorry for getting a bit annoyed earlier.  It's been a long, long day...)

**Comment by chengzhuzhang** [comment]
Thank you for getting to it so quickly. (and the day is indeed too long, looking at current Berlin time...)
