### ISSUE TITLE
Add location of mbtempest

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/mache#4]
We likely need the location of system compiled `mbtempest` on each supported machine (if any).

**Comment by xylar** [comment]
@vijaysm and @iulian787, can you provide me with a list of locations and the compiler and type of MPI you used to build each?

**Comment by xylar** [comment]
Unless `mbtempest` is built statically, we will need to coordinate which compiler and MPI were used to build each with the modules and compilers used in E3SM-Unified.

**Comment by vijaysm** [comment]
@xylar just a note that there is a lot of info in the confluence page [1]. Yes we should agree on some better way to propagate this information. Perhaps a mbtempest.env.sh file that can be sourced on the LCF machines could simplify all of this. 

[1] https://acme-climate.atlassian.net/wiki/spaces/ED/pages/932380820/Offline+remapping+workflow+with+mbtempest

**Comment by xylar** [comment]
It seems like the way this will be handled is to install MOAB as part of E3SM-Unified, so `mbtempest` will be available in the same way as any other software.
