### ISSUE TITLE
Update Cori paths

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/mache#52]
Currently, for Cori-Haswell, `base_url = https://portal.nersc.gov/project/e3sm/` (https://github.com/E3SM-Project/mache/blob/main/mache/machines/cori-haswell.cfg#L37). However, the path should use `/cfs/` rather than `/project/`. (It's also possible I've gotten mixed up on which is the correct path. Currently, https://portal.nersc.gov/project/e3sm/forsyth/ and https://portal.nersc.gov/cfs/e3sm/forsyth/ are identical).

**Comment by xylar** [comment]
I am happy to make this change but I am not aware of any problem with the current `project` path.

**Comment by forsyth2** [comment]
@chengzhuzhang -- do you know of any issues with the `/project/` URL? 

If not, there just might have been a miscommunication over the original web path change (e.g., https://github.com/E3SM-Project/e3sm_diags/pull/297, which changed "https://portal.nersc.gov/cfs/acme/" references to "https://portal.nersc.gov/cfs/e3sm/").

That said, it does look like our tool docs usually specify the `/cfs/` path rather than the `/project/` path -- e.g., https://e3sm-project.github.io/e3sm_diags/_build/html/master/quickguides/quick-guide-cori-haswell.html specifies `http://portal.nersc.gov/cfs/e3sm/<username>/` 

So, in any case, it would be good to standardize which web path we send users to.

**Comment by xylar** [comment]
Based on this documentation page, `cfs` seems to be right:
https://docs.nersc.gov/services/science-gateways/

**Comment by xylar** [comment]
@forsyth2, please make a PR and I'll test and merge it tomorrow.

**Comment by chengzhuzhang** [comment]
@xylar Thanks. I was looking into this and found the same nersc doc page. Right now the link with `poject/` points to `cfs/` so both links are working. As documented by NERSC using `cfs/` in the URL is the right thing, because they hope to be able to remove all references to the old filesystem before cfs.
