### ISSUE TITLE
Include mapping file directory

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/mache#53]
Currently, `zppy` requires the mapping file directory to be entered manually. If Mache could include this information, it would simplify `zppy` runs.

E.g.:
https://github.com/E3SM-Project/zppy/blob/main/tests/integration/template_complete_run.cfg#L6 -> `mapping_file = "#expand mapping_path#map_ne30pg2_to_cmip6_180x360_aave.20200201.nc"`
https://github.com/E3SM-Project/zppy/blob/main/tests/integration/utils.py ->
```
"mapping_path": "/home/ac.zender/data/maps/",
"mapping_path": "/compyfs/zender/maps/",
"mapping_path": "/global/homes/z/zender/data/maps/",
```

**Comment by forsyth2** [comment]
Presumably Mache could also sync the mapping files across these directories.

**Comment by xylar** [comment]
@forsyth2, we should discuss this.  I am not in favor of including anyone's home directory as an "official" shared directory on any HPC.  I think we need to find a standard place for these within the existing `diagnostics` directory on LCRC and sync them to other machines along with other diagnostics files.

@czender may have a different view on this so we should have a discussion about it either here or during our next E3SM tools meeting.

**Comment by czender** [comment]
I agree that the map-files and grid files should come from a standard directory, not a user's directory. What we have now developed organically (people asked me to generate maps for their favorite analysis grids) and not through planning.  So let's plan it. However, as you may know, there are already standard directories from which E3SM and some tools obtain grid and map files

```
https://web.lcrc.anl.gov/public/e3sm/inputdata
https://web.lcrc.anl.gov/public/e3sm/inputdata/cpl/gridmaps
https://web.lcrc.anl.gov/public/e3sm/inputdata/ocn/mpas-o/
```
Any solution should probably consider all needs, i.e., pre-processing (i.e., initial conditions), run-time, and postprocessing. Therefore @rljacob should be involved.

**Comment by doutriaux1** [comment]
@czender have you considered https://github.com/llnl/kosh for your data management? It allows for format and location independent data management.

**Comment by xylar** [comment]
@doutriaux1, thanks.  A brief look at the `kosh` page didn't make completely clear what problem this would solve for us.  Could you elaborate?

**Comment by doutriaux1** [comment]
essentially you can leave your files where ever you want, simply register your sim/ensembles in the store and associate any relevant file with them. After that you do not need to know where the file lives or what its format is. Even better you can move the files around and kosh will update the store for you (and all users) transparently. Kosh also has the notion of ensembles (something you guys do a lot) and schemas to ensure the metadata is valid.

**Comment by xylar** [comment]
@doutriaux1, that sounds interesting but maybe outside the scope of what we are working on here.  These mapping files would be associated with a given set of meshes but not necessarily specific simulations.  I think we do want to have the files in a specific, curated location.  I'm not looking to make it easier for anyone who wants to to add new mapping files.  But we'll keep Kosh in mind more for working with and sharing simulation output.

**Comment by rljacob** [comment]
We made a decision, not yet implemented, to put all grid files in inputdata/share/meshes.

A common location for mapping files hasn't been discussed but yes we should have one under inputdata

**Comment by rljacob** [comment]
If you have confluence access:  https://acme-climate.atlassian.net/wiki/spaces/EIDMG/pages/3335651401/Common+location+naming+for+mesh+grid+files.

**Comment by xylar** [comment]
It seems like diagnostics tools need our own (possibly redundant) copies of these mapping files for the time being.

**Comment by chengzhuzhang** [comment]
> It seems like diagnostics tools need our own (possibly redundant) copies of these mapping files for the time being.

@xylar I'm thinking along the same line... to have some redundancy in this case may be a straightforward solution.

**Comment by rljacob** [comment]
Diags needs some different maps from the model so yes it might make sense to have a separate dir even long term.   But we should have a common naming convention so we know a map with the same name in two locations is the same map.

**Comment by xylar** [comment]
I want to follow up from Thursday's meeting.  Can we agree on a location for mapping files?

Currently, MPAS-Analysis has directories for mapping files it uses:
```
/lcrc/group/e3sm/public_html/diagnostics/mpas_analysis/maps
/lcrc/group/e3sm/diagnostics_private/mpas_analysis/maps
```
We have considered some of the meshes with ice-shelf cavities to be "private" for awhile but I'm going to move them to the public diagnostics area right now.

Where to put other mapping files presumably depends on how specific they are likely to be to a given tool.  While other tools can use the MPAS-Analysis mapping files, they are intended for that tool and follow a naming convention that it expects.

The mapping files currently in @czender's directory are presumably used for multiple purposes, at least one of which is `zppy` if I understand correctly and another is `e3sm_to_cmip`.  So having these mapping files under a directory named after a tool likely isn't a good idea.

Alternative suggestions?

Another consideration is that we need to keep permissions consistent.  I suggest files be world readable and owner and group writable.  They need to be in the `e3sm` group.  Any concerns there?

**Comment by czender** [comment]
How about at the same level as `e3sm-unified`, since that exists on all machines? For example,

```
/lcrc/soft/climate/maps
/lcrc/soft/climate/e3sm-unified
```
Or a child of the diagnostics that already holds `mpas_analysis`, e.g.,
```
/lcrc/group/e3sm/public_html/diagnostics/maps
/lcrc/group/e3sm/public_html/diagnostics/mpas_analysis
```

**Comment by xylar** [comment]
@czender, I like the suggestion of
```
/lcrc/group/e3sm/public_html/diagnostics/maps
```

I don't think it would be a good idea to place the mapping files outside of the `diagnostics` directory both because the `e3sm-unified` directories are typically in a location designated for software, not data files and because `mache` is currently only designed to sync files within the `diagnostics` directories (public and private).

**Comment by chengzhuzhang** [comment]
Thank you for following up on this @xylar and @czender !
Adding one more vote for /lcrc/group/e3sm/public_html/diagnostics/maps
yes, besides Mpas-analysis, zppy, e3sm_to_cmip(e2c), and the publication workflow which depends on e2c are all customers. Having a `maps` directory outside of a specific tool directory makes good sense.

**Comment by xylar** [comment]
I'm going to close this issue as resolved.
