### ISSUE TITLE
Update diagnostics dir on Acme1?

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/mache#66]
The diagnostics directory no longer exists on Acme1:
https://github.com/E3SM-Project/mache/blob/main/mache/machines/acme1.cfg#L18

@chengzhuzhang, @forsyth2, do we need to update it?

**Comment by tomvothecoder** [comment]
I created the directory: `/p/user_pub/e3sm/diagnostics`.

Let me know what the next steps are (`mache sync diags from chrysalis`?).

**Comment by xylar** [comment]
That's great!  The next step would be to set up your ssh keys so you can log into chrysalis from acme1.  After than, you will need to clone a branch of `mache` that I will post soon, make a dev conda environment and then run `mache sync diags from chrysalis -u <ac.username>`.  I'll post more complete instructions soon.

**Comment by xylar** [comment]
Full instructions:
```
mkdir mache
cd mache
git clone git@github.com:E3SM-Project/mache.git
cd mache
git remote add xylar/mache git@github.com:xylar/mache.git
git fetch --all -p
git worktree add ../fix_acme1_diags_dir
cd ../fix_acme1_diags_dir
git reset --hard xylar/mache/fix_acme1_diags_dir
mamba create -y -n mache_dev --file spec-file.txt
conda activate mache_dev
python -m pip install -e .
mache sync diags from chrysalis -u ac.tvo
```
