### ISSUE TITLE
Use `$E3SMU_MACHINE` environment variable as a fallback

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/mache#83]
This could be used as a fallback if the machine cannot be discovered in the current way.

See https://github.com/E3SM-Project/zppy/issues/383#issue-1497166101 for more info.

**Comment by golaz** [comment]
Some way to correctly identify compute nodes for our different machines would be helpful, especially now that `mache` gaining more traction (as it should).

**Comment by xylar** [comment]
@golaz, there should be a way to identify a machine when `mache` gets installed into a conda environment and save that information in a way that an environment variable gets set on activation.  I don't exactly know how this works and haven't found a suitable example to work from yet but I know that it can be done (for example I see evidence that one of the packages involved `jupyter` does this).

My question for you is, do you ever try create the conda environment you use to run `zppy` and friends from a compute node?  Or is that step at least reliably done on a login node?

**Comment by xylar** [comment]
I have implemented a different fallback instead of `$E3SMU_MACHINE` (which is not very general) in #84.
